[2024-05-02T09:05:12.497-0500] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-02T09:05:12.504-0500] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scenario_two_v3.second_task manual__2024-05-02T14:05:09.082432+00:00 [queued]>
[2024-05-02T09:05:12.506-0500] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scenario_two_v3.second_task manual__2024-05-02T14:05:09.082432+00:00 [queued]>
[2024-05-02T09:05:12.506-0500] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-02T09:05:12.511-0500] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): second_task> on 2024-05-02 14:05:09.082432+00:00
[2024-05-02T09:05:12.513-0500] {standard_task_runner.py:63} INFO - Started process 39222 to run task
[2024-05-02T09:05:12.516-0500] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'scenario_two_v3', 'second_task', 'manual__2024-05-02T14:05:09.082432+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/dotnet_dag.py', '--cfg-path', '/var/folders/14/31_1v10s5nvcqyswsggcn5vh0000gn/T/tmps6sin1hw']
[2024-05-02T09:05:12.517-0500] {standard_task_runner.py:91} INFO - Job 23: Subtask second_task
[2024-05-02T09:05:12.531-0500] {task_command.py:426} INFO - Running <TaskInstance: scenario_two_v3.second_task manual__2024-05-02T14:05:09.082432+00:00 [running]> on host nestors-macbook.attlocal.net
[2024-05-02T09:05:12.555-0500] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='nestor' AIRFLOW_CTX_DAG_ID='scenario_two_v3' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-02T14:05:09.082432+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-02T14:05:09.082432+00:00'
[2024-05-02T09:05:12.556-0500] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-02T09:05:12.562-0500] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/14/31_1v10s5nvcqyswsggcn5vh0000gn/T
[2024-05-02T09:05:12.563-0500] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo currently in $(pwd)']
[2024-05-02T09:05:12.565-0500] {subprocess.py:86} INFO - Output:
[2024-05-02T09:05:12.568-0500] {subprocess.py:93} INFO - currently in /private/var/folders/14/31_1v10s5nvcqyswsggcn5vh0000gn/T/airflowtmpmlsdy6w7
[2024-05-02T09:05:12.568-0500] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-02T09:05:12.569-0500] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-02T09:05:12.576-0500] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=scenario_two_v3, task_id=second_task, execution_date=20240502T140509, start_date=20240502T140512, end_date=20240502T140512
[2024-05-02T09:05:12.623-0500] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-02T09:05:12.628-0500] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-02T09:05:12.629-0500] {local_task_job_runner.py:222} INFO - ::endgroup::
